name: Build PolmineR Dev Image  

on:
  push:
      branches:
          - "dev"
          

jobs:
  build-devimage:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set Version
        run: |
          echo "POLMINE_VERSION=$(wget -qO-  https://raw.githubusercontent.com/PolMine/polmineR/dev/DESCRIPTION  | grep "Version:" | sed 's/^.*: //')" >>  $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_OWNER }}
          password: ${{ secrets.CR_PAT }}
      
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Docker/polminer/Dockerfile
          platforms: linux/amd64
          push: true
          build-args: branch=dev
          tags: |
            ghcr.io/polmine/polminer-dev:latest
            ghcr.io/polmine/polminer-dev:${{env.POLMINE_VERSION}}
